### ISSUE TITLE
HostPlumber VFIO-PCI Without SRIOV

### ISSUE THREAD

**Issue by infinitydon** [platform9/luigi#114]
Hi,

I am currently trying to use the HostPlumber to assign VFIO-PCI driver to specific VFs (NICs are already VFs so SRIOV will be disabled for them), the config I am using is below but it is not working:
```
apiVersion: plumber.k8s.pf9.io/v1
kind: HostNetworkTemplate
metadata:
  name: proxmoxnics
spec:
  sriovConfig:
    - pciAddr: 0000:00:13.0
      vfDriver: vfio-pci
    - pciAddr: 0000:00:14.0
      vfDriver: vfio-pci
```

Is the above supported or HostPlumber can only work with SRIOV PFs?

Thanks
